version: '3.5'

services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: dg-postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: dg-app
#    environment:
#      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./code:/code
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - /code/node_modules

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: dg-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
